spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-auth
server:
  port: 9100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


#  MYSQL_HOST=localhost;MYSQL_DATABASE=authdb;MYSQL_USER=root;MYSQL_PASSWORD=root